### ISSUE TITLE
Bluetooth connectivity issue

### ISSUE THREAD

**Issue by niksart** [intelino-code/intelino-trainlib-py#5]
Hello,
I am reporting here a connectivity issue with the intelino J1 train. I am connecting to the train through the integrated Bluetooth connector of my pc (version 5.0). I am using python 3.8.8.

First of all, I switch on the train.

Then, when running `python3 -m intelino.scan`, I can see the train.

```
Trains (1):
00:A0:50:A3:46:EC : intelino J-1 (RSSI -59)
```

But when I execute the first example `python 01_get_train_info.py`, I get either this error:

```
Traceback (most recent call last):
  File "01_get_train_info.py", line 25, in <module>
    main()
  File "01_get_train_info.py", line 14, in main
    with TrainScanner() as train:
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train_scanner.py", line 50, in __enter__
    self.blocking_train = self.get_train()
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train_scanner.py", line 82, in get_train
    return Train(train)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 68, in __init__
    self.__execute(self.__setup())
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 104, in __execute
    return asyncio.run_coroutine_threadsafe(
  File "/home/niksart/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/niksart/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 71, in __setup
    await self.__train.connect()
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/train.py", line 84, in connect
    return await self._device.connect(force, **kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/train_ble_device.py", line 79, in connect
    connected = await self._driver.connect(**kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/drivers/bleak_driver.py", line 49, in connect
    await self.__bleak_client.start_notify(
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/__init__.py", line 834, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/client.py", line 958, in start_notify
    assert_reply(reply)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
```

or this error:

```
Traceback (most recent call last):
  File "01_get_train_info.py", line 25, in <module>
    main()
  File "01_get_train_info.py", line 14, in main
    with TrainScanner() as train:
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train_scanner.py", line 50, in __enter__
    self.blocking_train = self.get_train()
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train_scanner.py", line 82, in get_train
    return Train(train)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 68, in __init__
    self.__execute(self.__setup())
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 104, in __execute
    return asyncio.run_coroutine_threadsafe(
  File "/home/niksart/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/niksart/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelino/trainlib/train.py", line 71, in __setup
    await self.__train.connect()
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/train.py", line 84, in connect
    return await self._device.connect(force, **kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/train_ble_device.py", line 79, in connect
    connected = await self._driver.connect(**kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/intelino/trainlib_async/drivers/bleak_driver.py", line 41, in connect
    connected = await self.__bleak_client.connect(**kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/client.py", line 268, in connect
    await self.get_services(
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/client.py", line 656, in get_services
    self.services = await manager.get_services(
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/manager.py", line 644, in get_services
    await self._wait_for_services_discovery(device_path)
  File "/home/niksart/kDrive/intelino/intelino-trainlib-py/intelinoenv/lib/python3.8/site-packages/bleak/backends/bluezdbus/manager.py", line 779, in _wait_for_services_discovery
    raise BleakError("failed to discover services, device disconnected")
bleak.exc.BleakError: failed to discover services, device disconnected
```

I cannot predict the type of the error, it seems quite random to me.

I tried with the last version of the library, and with the release 1.0.0, and I have issues with both. I also tried with the async library and I have the same problem.

Please tell me if I can be of any help, or if any information is missing.

Thanks a lot for the help!

Edit:

This error in on OS Ubuntu 22.02 LTS, I did not encounter this problem on Windows 11

**Comment by petrusek** [comment]
Hi, connectivity issues are sometimes really hard to reproduce and they are sometimes also hard to fix.

For this purpose we have a "raw" connection file in the async repo https://github.com/intelino-code/intelino-trainlib-async-py/blob/master/examples/bleak/raw_bleak_connection.py ... you can copy its content, update your trains' address and experiment. You could also try a different bleak version...

Sorry for the late reply, I hope this will help (at least a bit).
